class AppStrings {
  static const Map<String, Map<String, String>> localizedValues = {
    'en': {
      'app_name': 'KARIGASETU AI',
      'tagline': 'From Craft to Commerce',
      'greeting': 'Good Morning',
      'hero_subtitle': 'Your craft is ready for the world.',
      'monthly_sales': 'MONTHLY SALES',
      'products': 'Products',
      'buyers': 'Buyers',
      'ai_insight_title': '✨ AI BUSINESS INSIGHT',
      'ai_scan': 'AI SCAN',
      'speak_prompt': '🎙️ Speak instead of typing',
      'scanning': 'Understanding your craft...',
      'rec_price': 'RECOMMENDED PRICE',
      'market_range': 'Market range',
      'expected_margin': 'Expected margin',
      'approve': 'Approve & Publish',
      'search_hint': 'Search: e.g. "100 handmade bags under ₹1200"',
      'ask_ai': 'Ask AI Co-Pilot',
      'orders': 'Orders',
      'sync_status': '3 items waiting to sync',
    },
    'te': {
      'app_name': 'కారిగసేతు AI',
      'tagline': 'చేతిపని నుండి వాణిజ్యానికి',
      'greeting': 'శుభోదయం',
      'hero_subtitle': 'మీ చేతివృత్తి ప్రపంచానికి సిద్ధంగా ఉంది.',
      'monthly_sales': 'నెలవారీ అమ్మకాలు',
      'products': 'ఉత్పత్తులు',
      'buyers': 'కొనుగోలుదారులు',
      'ai_insight_title': '✨ AI వ్యాపార సలహా',
      'ai_scan': 'AI స్కానింగ్',
      'speak_prompt': '🎙️ టైప్ చేయడానికి బదులుగా మాట్లాడండి',
      'scanning': 'మీ చేతిపనిని గుర్తిస్తున్నాము...',
      'rec_price': 'సిఫార్సు చేయబడిన ధర',
      'market_range': 'మార్కెట్ పరిధి',
      'expected_margin': 'ఆశించిన లాభం',
      'approve': 'ఆమోదించి ప్రచురించండి',
      'search_hint': 'శోధించండి: ఉదా. "₹1200 లోపు 100 చేతితో చేసిన బ్యాగులు"',
      'ask_ai': 'AI సలహా అడగండి',
      'orders': 'ఆర్డర్లు',
      'sync_status': '3 అంశాలు సమకాలీకరణ కోసం వేచి ఉన్నాయి',
    },
    'hi': {
      'app_name': 'कारीगासेतु AI',
      'tagline': 'शिल्प से व्यापार तक',
      'greeting': 'शुभ प्रभात',
      'hero_subtitle': 'आपकी कला दुनिया के लिए तैयार है।',
      'monthly_sales': 'मासिक बिक्री',
      'products': 'उत्पाद',
      'buyers': 'खरीदार',
      'ai_insight_title': '✨ AI व्यावसायिक सुझाव',
      'ai_scan': 'AI स्कैन',
      'speak_prompt': '🎙️ टाइप करने के बजाय बोलें',
      'scanning': 'आपकी शिल्पकारी को समझा जा रहा है...',
      'rec_price': 'अनुशंसित मूल्य',
      'market_range': 'बाजार सीमा',
      'expected_margin': 'अपेक्षित लाभ',
      'approve': 'स्वीकृत कर प्रकाशित करें',
      'search_hint': 'खोजें: जैसे "₹1200 से कम में 100 हस्तनिर्मित बैग"',
      'ask_ai': 'AI से सलाह लें',
      'orders': 'ऑर्डर',
      'sync_status': '3 आइटम सिंक होने की प्रतीक्षा में',
    }
  };

  static String get(String key, {String lang = 'en'}) {
    return localizedValues[lang]?[key] ?? localizedValues['en']?[key] ?? key;
  }
}
